###### ERRORS

ERROR_GRIPPER_FAILED = (7,'gripper opening failed')
ERROR_LINEAR_MOVEMENT_FAILED = (5,
                'gary linear motion command failed')
ERROR_GRIPPER_DETACHMENT_FAILED = (3,'gripper detachment failed')
ERROR_STILL_ATTACHED = (1,'cart still attached')
ERROR_TIMEOUT_REACHED = (2,f'loop timeout reached')


## Attaching
MAX_ATTEMPTS = 10
ATTEMPTS_BEFORE_VIBRATION = 5

## Geometric parameters
DISTANCE_BETWEEN_SRF_SENSORS = 23.5
MAX_SRF_VALUE = 150.0
CART_MAX_DISTANCE = 80.0

MAX_MOVING_VELOCITY = 0.3
VELOCITY_KP = 0.0015
VERIFICATION_VELOCITY = 0.0001
VERIFICATION_ANGLE = 2.0
VERIFICATION_DISTANCE = 1.2


FILTER_WEIGHT = 0.1
SRF_SENSOR_ID_RIGHT = '2'
SRF_SENSOR_ID_LEFT = '5'

### Gripper parameters
GRIPPER_OPEN_PRESSURE_CONST = 0.5
GRIPPER_CLOSE_PRESSURE_CONST = 0.8
GRIPPER_OPEN_POSITION = 1.0
GRIPPER_CLOSE_POSITION = 0.0
GRIPPER_VELOCITY = 0.2

POSITION_ERROR_MARGIN = 0.1
FULL_APP_TIMEOUT = 30.0

# ERROR_COULDNT_ATTACH_TO_CART = (1, "Couldn't attach to cart")
