


###### ERRORS

ERROR_SENSOR_NOISE = (9,'attach failed, IR sensor recive too much noise')
ERROR_CART_NOT_GETTING_CLOSER = (8,'attach failed, cart pushed')
ERROR_GRIPPER_FAILED = (7,'gripper opening failed')
ERROR_ROTATION_MOVEMENT_FAILED = (6,'rotation motion command failed')
ERROR_LINEAR_MOVEMENT_FAILED = (5,
                'gary linear motion command failed')
ERROR_APPROACH_FAILED = (4,

                'approach to tag failed')
ERROR_GRIPPER_ATTACHMENT_FAILED = (3,'gripper attachment failed')
ERROR_CART_NOT_ATTACHED = (2,'cart was not attached')
ERROR_TIMEOUT_REACHED = (1,f'loop timeout reached')
ERROR_CART_NOT_ACCESSABLE = (0, 'cart is too far or not accessable,')




###### ANGLE ADJUSTMENT STATE PARAMETERS
ROTATING_DELTA_MIN = 100.0
ROTATING_CONST = 10.0
ROTATING_ANGULAR_SPEED = 2.0
NORMALIZED_DELTA_MAX = 0.4
NORMALIZED_DELTA_MIN = 0.4

DEFAULT_MAX_ANGLE_STEP = 15.0
FULL_APP_TIMEOUT = 45.0

###### ATTACHING STATE PARAMETERS
# ATACHING_DISTANCE_MIN = 250
ATACHING_DISTANCE_MIN = 900
# ATACHING_DISTANCE_MAX = 200
ATACHING_DISTANCE_MAX = 370
CART_MAX_DISTANCE = 80.0

###### LINEAR MOVING STATE PARAMETER
MIN_LINEAR_MOVING_VELOCITY = 0.005
MAX_LINEAR_MOVING_VELOCITY = 0.05

###### VERIFICATION STATE PARAMETER
VERIFICATION_DISTANCE = 3.5
POSITION_VERIFICATION_MAX_INDEX = 5.0


###### CART GRIPPER PARAMETERS
GRIPPER_OPEN_PRESSURE_CONST = 1.0
GRIPPER_CLOSE_PRESSURE_CONST = 0.9
GRIPPER_OPEN_POSITION = 1.0
GRIPPER_CLOSE_POSITION = 0.0
GRIPPER_ATTACHED_POSITION = 0.003
GRIPPER_ATTACHED_THRESHOLD = 0.02

###### PRE ATTACH  PARAMETERS
PRE_ATTACH_ANGLE_ROTATION = 180.0
PRE_ATTACH_RUTATION_SPEED = 20.0

###### SENSOR PARAMETERS
IR_SENSOR_ID_RIGHT = 2
IR_SENSOR_ID_LEFT = 1
IR_SENSOR_MAX_VALUE_VERIFICATION = 2000
SRF_NOISE_VERIFICATION_DISTANCE = 55.0
SRF_SENSOR_ID_CENTER = 4

###### APPROACH PARAMETERS
CAMERAS_TO_USE = ['cv_top', 'nav_top']
MAX_ANGLE_ERROR_ALLOWED = 1
MAX_Y_ERROR_ALLOWED = 0.02
DEFAULT_FINAL_APPROACH_DISTANCE = 0.5
DEFAULT_FIRST_APPROACH_DISTANCE = 1.0



###### ERRORS

ERROR_CART_NOT_GETTING_CLOSER = (8,'attach failed, cart pushed')
ERROR_GRIPPER_FAILED = (7,'gripper opening failed')
ERROR_ROTATION_MOVEMENT_FAILED = (6,'rotation motion command failed')
ERROR_LINEAR_MOVEMENT_FAILED = (5,
                'gary linear motion command failed')
ERROR_GRIPPER_ATTACHMENT_FAILED = (3,'gripper attachment failed')
ERROR_CART_NOT_ATTACHED = (1,'cart was not attached')
ERROR_TIMEOUT_REACHED = (2,f'loop timeout reached')
ERROR_CART_NOT_ACCESSABLE = (0, 'cart is too far or not accessable,')
ERROR_OBSTACLE_IDENTIFIED = (9,'obstacle detected behind gary')
ERROR_SRF_READING_FAILED = (10,'fail to read SRF value OR got only nan values')

###### Rotating

ROTATING_DISTANCE = 30.0
ROTATING_DISTANCE_AV = 20.0
ROTATING_ANGLE_MIN = 3.5
ROTATING_CONST = 100.0
ROTATING_ANGULAR_SPEED = 30.0
ROTATION_KP = 0.7
MIN_STARTING_ANGLE = 2.0
MAX_ANGLE_CORRECTION_ATTEMPTS = 8.0
MIN_ROTATION_ANGLE_STEP = 1.0
MAX_ANGLE_STEP = 10.0
VERIFICATION_ANGLE = 2.0

###### Attaching
MAX_ATTEMPTS = 8
ATTEMPTS_BEFORE_VIBRATION = 5
ATACHING_DISTANCE_MIN = 4.2
ATACHING_DISTANCE_MAX = 4.7
ATACHING_ANGLE_MAX = 2.0

###### linear movement

MAX_MOVING_VELOCITY = 0.3
VELOCITY_KP = 0.0015
VERIFICATION_VELOCITY = 0.0001

###### Geometric parameters
DISTANCE_BETWEEN_SRF_SENSORS = 23.5
MAX_SRF_VALUE = 150.0
CART_MAX_DISTANCE = 70.0


###### SRF parameters
VERIFICATION_DISTANCE = 1.2
MAX_PUSHING_INDEX = 3.0
FILTER_WEIGHT = 0.1
SRF_SENSOR_ID_RIGHT = '2'
SRF_SENSOR_ID_LEFT = '5'
SRF_SENSOR_ID_MIDDLE = '4'
NOISE_MARGIN = 0.05
POSITION_ERROR_MARGIN = 0.2

###### pushing cart identifing parameters
PUSHING_IDENTIFIER_DISTANCE = 6.0

###### Obstacle avoidence
OBSTACLE_DISTANCE_PARAMETER = 0.8
MAX_OBSTACLE_INDEX = 5
OBSTACLE_SLEEPING_TIME = 4.0
OBSTACLE_ENABLE_MIN_DISTANCE = 20.0
OBSTACLE_DETECTED_RATIO = 1.5
NON_OBSTACLE_DETECTED_RATIO = 0.6

###### UI
SOUND_VOLUME = 10
AUDIO_PATH = 'dat:pre_defined_audio'

###### Gripper parameters
GRIPPER_OPEN_PRESSURE_CONST = 0.5
GRIPPER_CLOSE_PRESSURE_CONST = 0.6
GRIPPER_OPEN_POSITION = 1.0
GRIPPER_CLOSE_POSITION = 0.0
GRIPPER_VELOCITY = 1.0
GRIPPER_TIMEOUT = 20.0

###### extra timeout
TIMEOUT_180 = 20.0

###### DEFAULT_SETUP_ARGS
GRIPPER_ACTUAL_DESIRED_POSITION = 0.168
FULL_APP_TIMEOUT = 70.0
DEFUALT_ROTATING_180 = False
REVERSE_BEEPING_ALERT = False ### this version not support beeping
