###### ERRORS

ERROR_CART_NOT_GETTING_CLOSER = (8,'attach failed, cart pushed')
ERROR_GRIPPER_FAILED = (7,'gripper opening failed')
ERROR_ROTATION_MOVEMENT_FAILED = (6,'rotation motion command failed')
ERROR_LINEAR_MOVEMENT_FAILED = (5,
                'gary linear motion command failed')
ERROR_GRIPPER_ATTACHMENT_FAILED = (3,'gripper attachment failed')
ERROR_CART_NOT_ATTACHED = (1,'cart was not attached')
ERROR_TIMEOUT_REACHED = (2,f'loop timeout reached')
ERROR_CART_NOT_ACCESSABLE = (0, 'cart is too far or not accessable,')

## Rotating

ROTATING_DISTANCE = 30.0
ROTATING_DISTANCE_AV = 20.0
ROTATING_ANGLE_MIN = 3.5
ROTATING_CONST = 100.0
ROTATING_ANGULAR_SPEED = 30.0
ROTATION_KP = 0.7
MIN_STARTING_ANGLE = 3.0
MAX_ANGLE_CORRECTION_ATTEMPTS = 8.0
MIN_ROTATION_ANGLE_STEP = 1.0
MAX_ANGLE_STEP = 10.0


## Attaching
MAX_ATTEMPTS = 8
ATTEMPTS_BEFORE_VIBRATION = 5
ATACHING_DISTANCE_MIN = 4.2
ATACHING_DISTANCE_MAX = 4.7
ATACHING_ANGLE_MAX = 2.0

## Geometric parameters
DISTANCE_BETWEEN_SRF_SENSORS = 23.5
MAX_SRF_VALUE = 150.0
CART_MAX_DISTANCE = 70.0

MAX_MOVING_VELOCITY = 0.3
VELOCITY_KP = 0.0015
VERIFICATION_VELOCITY = 0.0001
VERIFICATION_ANGLE = 2.0
VERIFICATION_DISTANCE = 1.2
MAX_PUSHING_INDEX = 3.0
FILTER_WEIGHT = 0.1
SRF_SENSOR_ID_RIGHT = '2'
SRF_SENSOR_ID_LEFT = '5'

NOISE_MARGIN = 0.05
PUSHING_IDENTIFIER_DISTANCE = 6.0
POSITION_ERROR_MARGIN = 0.15

### Gripper parameters
GRIPPER_OPEN_PRESSURE_CONST = 0.5
GRIPPER_CLOSE_PRESSURE_CONST = 0.8
GRIPPER_OPEN_POSITION = 1.0
GRIPPER_CLOSE_POSITION = 0.0
GRIPPER_VELOCITY = 0.2


### DEFAULT_SETUP_ARGS
GRIPPER_ACTUAL_DESIRED_POSITION = 0.21
FULL_APP_TIMEOUT = 60.0
DEFUALT_ROTATING_180 = False
